### PR TITLE
Fix: Clear empty WHERE rows

### LINKED ISSUE #121: When removing a where filter the whole line should be removed.
Happening: If we have multiple AND where filters and you remove the first of them the row is still rendered but with a [+] icon.
Expected: The whole row should be removed.

### PR DESCRIPTION
**Pull request by joshhunt**
Fixes #121

### CODE REVIEW

File: src/editor/components/QueryEditorRepeater.tsx [hunk 1]
```diff
@@ -47,9 +51,9 @@ export const QueryEditorRepeater: React.FC<Props> = props => {
 
   return (
     <>
-      {value.expressions.map((val, idx) => {
+      {Array.from(value.expressions).map((val, idx) => {
         return (
-          <React.Fragment key={`${id}-${idx}`}>
```
Comment (sunker) [inline src/editor/components/QueryEditorRepeater.tsx:52]: Yes!!

**Review by sunker — APPROVED** [review]
Nice! Tested and it works as expected
