### PR TITLE
Fix: Invalid code editor loaded for Grafana versions that don't follow semantic versioning

### LINKED ISSUE #505: Invalid code editor loaded for Grafana versions that don't follow semantic versioning
If the version of Grafana isn't a valid semantic version then the code editor for Grafana pre-8.5 will be loaded. This causes issues with other panels and leads to Grafana crashing.

### PR DESCRIPTION
**Pull request by aangelisc**
Will correctly handle security releases by coercing the version into a value that follows semver rules.

Fixes #505

### CODE REVIEW

File: src/components/LegacyQueryEditor/RawQueryEditor.tsx [hunk 1]
```diff
@@ -41,6 +41,15 @@ interface Worker {
 // that includes fixes required for auto-completion to work.
 // Remove this code once Grafana 8.5 is the minimal version supported
 function gtGrafana8_5() {
+  const version = config.buildInfo.version
+  const isValid = valid(config.buildInfo.version)
```
Comment (asimpson) [inline src/components/LegacyQueryEditor/RawQueryEditor.tsx:45]: Nit: could just pass `version` to `valid` no?

File: src/components/LegacyQueryEditor/RawQueryEditor.tsx [hunk 2]
```diff
@@ -41,6 +41,15 @@ interface Worker {
...
+  // Assume that a security release will be of the form 'w.x.y.z' - Pre releases of the form 'w.x.y-pre.z' are already valid
+  const isSecurityRelease = version.split('.').length > 3
+  if (!isValid && isSecurityRelease) {
+    // Coerce will drop the z in 'w.x.y.z' leaving just the major-minor-patch version
+    const coercedValue = coerce(version)
+    return coercedValue ? gte(coercedValue, '8.5.0') : null;
+  }
   return valid(config.buildInfo.version) && gte(config.buildInfo.version, '8.5.0');
```
Comment (asimpson) [inline src/components/LegacyQueryEditor/RawQueryEditor.tsx:53]: Nit: could return `isValid` here instead of re-running `valid`. Could also pass `version` instead of the full object address again.

**Review by asimpson — APPROVED** [review]
🚀 nice work!

✅ tests pass 
✅ solves the issue

I left two nit comments but this works for me!

**Review by andresmgot — APPROVED** [review]
