### PR TITLE
Correctly cast dynamically typed columns

### LINKED ISSUE #429: Dynamic columnn not being casted
**What happened**:

When using a dynamic column in the Group by or Aggregate field, it's necessary to cast the value to a simple type: e.g. `sum(col)` -> `sum(tolong(col))`.

The problem is that the logic, at the moment, to differ is a column is dynamic, is checking if it's part of an object:

https://github.com/grafana/azure-data-explorer-datasource/blob/main/src/KustoExpressionParser.ts#L402
```ts
const isDynamic = (column: string): boolean => {
  return !!(column && column.indexOf('[') > -1) || !!(column && column.indexOf('todynamic') > -1);
};
```

So if a column is a simple value, it won't be detected as dynamic, skiping the casting.

We need to fix that logic.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**

**Anything else we need to know?**:

**Environment**:

- Grafana version:
- Plugin version: 4.1.2
- OS Grafana is installed on:
- User OS & Browser:
- Others:

### PR DESCRIPTION
**Pull request by aangelisc**
Fixes #429 where 'simple' dynamic columns were not being appropriately cast in `group by` and `summarize` statements.

### CODE REVIEW

File: src/KustoExpressionParser.ts [hunk 1]
```diff
@@ -399,17 +399,23 @@ const defaultTimeColumn = (columns?: AdxColumnSchema[], expression?: QueryExpres
   return toType(column.CslType, column.Name);
 };
 
-const isDynamic = (column: string): boolean => {
-  return !!(column && column.indexOf('[') > -1) || !!(column && column.indexOf('todynamic') > -1);
+const isDynamic = (column: string | AdxColumnSchema | undefined): boolean => {
+  if (column && typeof column === 'object') {
+    return column.Type === 'dynamic';
+  } else if (typeof column === 'string') {
+    return !!(column && column.indexOf('[') > -1) || !!(column && column.indexOf('todynamic') > -1);
```
Comment (andresmgot) [inline src/KustoExpressionParser.ts:406]: we probably don't need this case anymore, right? And we can simplify the column type to be only `AdxColumnSchema | undefined`

File: src/datasource.ts [hunk 2]
```diff
@@ -383,13 +383,13 @@ const recordSchemaArray = (name: string, types: AdxSchemaDefinition[], result: A
   if (types.every((t) => typeof t === 'string' && toPropertyType(t) === QueryEditorPropertyType.Number)) {
     // If all the types are numbers, the double takes precedence since it has more precission.
     const cslType = types.find((t) => typeof t === 'string' && (t === 'double' || t === 'real')) || defaultCslType;
-    result.push({ Name: name, CslType: cslType as string });
+    result.push({ Name: name, CslType: cslType as string, Type: 'dynamic' });
```
Comment (andresmgot) [inline src/datasource.ts:386]: I don't think we should use the `Type` field since that field is already a used field in a schema and it should be the [".NET equivalent type"](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/). I would instead extend the AdxColumnSchema type so we can inject some metadata into it:

```tsx
export interface AdxColumnSchema {
  Name: string;
  CslType: string;
  Type?: string;
  CslDefaultValue?: string;
  // tracking internally if a type is inferred from a dynamic type
  isDynamic?: boolean;
}
```

**Review by andresmgot — COMMENTED** [review]
Nice solution! I just have a couple of minor suggestions

File: src/datasource.ts (hunk 2 above)
Comment (aangelisc) [reply src/datasource.ts:386]: Good shout 😊

File: src/KustoExpressionParser.ts [hunk 3]
```diff
@@ -399,17 +406,21 @@ const defaultTimeColumn = (columns?: AdxColumnSchema[], expression?: QueryExpres
...
 
-const isDynamic = (column: string): boolean => {
-  return !!(column && column.indexOf('[') > -1) || !!(column && column.indexOf('todynamic') > -1);
+const isDynamic = (column: AdxColumnSchema | undefined): boolean => {
+  if (column && column.isDynamic) {
+    return column.isDynamic;
+  } else {
+    return false;
+  }
 };
```
[the remark this answers is not in the document]
Comment (aangelisc) [reply src/KustoExpressionParser.ts]: Good catch 😊

**Review by andresmgot — APPROVED** [review]
LGTM!

File: src/datasource.ts (hunk 2 above)
Comment (andresmgot) [inline src/datasource.ts:386]: it seems that you forgot to update these to  use `isDynamic` instead
